name: default
description: Original dashboard theme
dashboard_title: Deltabot Simulator

# Palette assignments for trace coloring
palettes:
  primary: 'rgb'      # Default palette for most traces
  secondary: 'space'     # Secondary palette for complementary data
  tertiary: 'winter'      # Tertiary palette for additional data

colors:
  primary_bg: &color_primary_bg "#ffffff"
  secondary_bg: &color_secondary_bg "#f8f9fa"
  text_primary: &color_text_primary "#4b4d51"
  text_secondary: &color_text_secondary "#6e7073"
  border: &color_border "#dee2e6"
  accent: &color_accent "#343538"

global-styles:
  border:
    bars: &border_style "1.25px solid #dee2e6"
  # box_shadow:
    # upper: &upper-shadow "0px 6px 10px 0px #000000 inset"
    # main: &main-shadow "0px -4px 6px 0px rgba(0, 0, 0, 0.1) inset, 0px 4px 6px 0px rgba(0, 0, 0, 0.1) inset"
    # footer: &footer-shadow "0px -6px 10px 0px #000000 inset"

fonts:
  monospace: &monospace_font "'DroidSansMonoNerdFontMono, 'monospace'"
  sans: &sans_font "'sans-serif'"
  title: &title_font "'DroidSansMonoNerdFontPropo', 'Arial'"
  tab: &tab_font "'DroidSansMonoNerdFontPropo', 'Arial'"
  body: &body_font "'DroidSansMonoNerdFontPropo', 'Arial'"
  plots: &plots_font "DroidSansMonoNerdFontPropo"
  footer: &footer_font "'DroidSansMonoNerdFontPropo', 'monospace'"
  table: &table_font "'DroidSansMonoNerdFontPropo', 'monospace'"
  hoverlabels: &hoverlabels_font "DroidSansMonoNerdFontPropo"

icons:
  tabs:
    robot-overview: ""
    actuator-dynamics: ""
    actuator-loads: ""
    end-affector-trajectory-spatial: ""
    joint-trajectories: ""
    end-affector-trajectory: ""
    summary-specifications: ""
    results-table: ""
    job-selector: ""

styles:
  header:
    textAlign: center
    fontFamily: *title_font
    fontSize: 3.5rem
    fontWeight: 600
    color: *color_text_primary
    height: 110px
    flex-shrink: 0
    background: *color_secondary_bg
    align-content: center
    margin-bottom: 0px
    text-transform: unset
    letter-spacing: 0.8rem

  tab:
    background: *color_primary_bg
    color: *color_text_secondary
    border: *border_style
    borderRadius: 18px
    padding: "0.5rem 1rem"
    fontFamily: *tab_font
    fontWeight: 600
    fontSize: 1.1em
    display: "flex"
    alignItems: center
    justifyContent: center
    lineHeight: 1.25
    maxWidth: 70%
    
  tab_selected:
    background: *color_accent 
    fontFamily: *tab_font
    borderRadius: 18px
    fontWeight: 800
    fontSize: 1.3rem
    fontStyle: bold
    color: "#ffffff"
    borderColor: *color_accent 
    display: "flex"
    alignItems: "center"
    justifyContent: "center"
    lineHeight: 1.25
    background: *color_accent 
    
  tab_container:
    background: *color_secondary_bg
    margin: 0rem
    padding: 0rem 4rem 0.5rem
    gap: 2rem
    justifyContent: center
    height: 80px
    flex-shrink: 0
    border-bottom: *border_style


  body_container:
    background: *color_primary_bg
    height: 100%
    margin: 0px
    fontFamily: *body_font
    display: flex
    flexDirection: column
    min-height: 100vh
    overflow: hidden  # prevent outer scroll
    
  main_container:
    background: *color_primary_bg
    flex: 1 1 auto
    padding: 0rem
    overflow-x: hidden
    overflow-y: auto

  graph_container:
    background: *color_primary_bg
    margin-top: 5px
    flex: 1 1 auto
    overflow-y: auto
    gap: 0rem
    width: 100%
    height: 100%
    # max-width: 1200px
    # min-width: 600px

  table_container:
    background: *color_primary_bg
    flex: 1 1 auto
    overflow-y: auto
    gap: 0rem;
    width: 100%;
    max-width: 1200px;
    min-width: 600px;
    
  footer:
    # position: fixed;
    # bottom: 0;
    # left: 0;
    width: 100%;
    textAlign: center
    padding: 1rem
    background: *color_secondary_bg
    color: *color_text_secondary
    borderTop: *border_style
    fontFamily: *footer_font
    fontWeight: 400
    fontSize: 1.2rem
    height: 60px
    z-index: 9999
    lineHeight: 1.25
    flex-shrink: 0
    # box-shadow: *footer-shadow

  dropdown-container:
    color: *color_text_primary
    background: *color_primary_bg
    fontFamily: *body_font
    fontSize: 1rem
    minWidth: 200px
    display: "block"
    padding: "1rem 10rem 1rem 10rem"

  dropdown:
    background: *color_secondary_bg
    border: *border_style
    borderRadius: 8px

plotly:
  layout:
    paper_bgcolor: "#ffffff"
    plot_bgcolor: "#ffffff"
    font:
      family: *plots_font
      size: 16
      color: *color_text_primary
    autosize: True
    title:
      y: 0.9
      x: 0.5
      xanchor: center
      yanchor: top
    # colorway: ["#007bff", "#28a745", "#dc3545", "#ffc107", "#17a2b8", "#6f42c1", "#e83e8c", "#fd7e14"]
    # margin: {l: 60, r: 60, t: 60, b: 60}
    xaxis:
      gridcolor: "#dee2e6"
      color: *color_text_primary
      linecolor: "#dee2e6"
      tickcolor: "#dee2e6"
      zerolinecolor: "#777777"
      zerolinewidth: 2
      title:
        font:
          weight: 400
      tickfont:
        weight: 400
    yaxis:
      gridcolor: "#dee2e6"
      color: *color_text_primary
      linecolor: "#dee2e6"
      tickcolor: "#dee2e6"
      zeroline: True
      zerolinecolor: "#777777"
      zerolinewidth: 2
      title:
        font:
          weight: 400
      tickfont:
        weight: 400
    yaxis2:
      zeroline: False
    showlegend: False
    scene:
      xaxis:
        gridcolor: "#dee2e6"
        backgroundcolor: "#ffffff"
        color: *color_text_primary
        autorange: False
        showgrid: True
        tick0: 0          # start of ticks
        dtick: 0.1        # spacing between ticks
      yaxis:
        gridcolor: "#dee2e6"
        backgroundcolor: "#ffffff"
        color: *color_text_primary
        showgrid: True
        autorange: False
        tick0: 0          # start of ticks
        dtick: 0.1        # spacing between ticks
      zaxis:
        gridcolor: "#dee2e6"
        backgroundcolor: "#ffffff"
        color: *color_text_primary
        showgrid: True
        autorange: False
        tick0: 0          # start of ticks
        dtick: 0.1        # spacing between ticks
      # aspectmode: manual
      # aspectratio: {x: 1, y: 1, z: 1}
    hoverlabel:
      font_size: 12
      font_family: *hoverlabels_font

  traces:
    default:
      marker: 
        size: 8
      line: 
        width: 3
      mode: lines+markers
      visible: true
      hovertemplate: "%{y:.3f}"

    traj:
      mode: lines
    traj.spatial:
      marker: 
        # line:
        #   width: 4
        #   colorscale: "Viridis"
        colorscale: "Viridis"
        size: 6
        # symbol: x-thin
    traj.spatial.3d:
      marker: 
        # line:
        #   width: 4
        #   colorscale: "Viridis"
        colorscale: "Viridis"
        size: 4
        # symbol: x
        colorbar: {"title": "Velocity [m/s]"}
        


    actuator:
      mode: lines
      hovertemplate: "%{y:.2f}"

    actuator.tn_curve:
      marker:
        line:
          width: 2
        size: 6
        symbol: x-thin
      mode: markers
      hovertemplate: "%{y:.2f}"

    # Robot-specific trace properties
    nacelle:
      marker: 
        size: 5
        color: "#6c757d"
      line: 
        color: "#6c757d"
        width: 5
      surfacecolor: "rgba(108,117,125,0.1)"
      surfaceaxis: 2
      visible: true
    base:
      marker: 
        size: 6
        color: "#495057"
      line: 
        color: "#495057"
        width: 8
      surfacecolor: "rgba(73,80,87,0.1)"
      surfaceaxis: 2
      visible: true
    proximal:
      marker: 
        size: 8
        color: "#007bff"
      line: 
        color: "#007bff"
        width: 7
      visible: true
    distal:
      marker: 
        size: 3
        color: "#17a2b8"
      line: 
        color: "#17a2b8"
        width: 4
      visible: true
    trajectory:
      marker: 
        size: 3
        color: "#28a745"
      line: 
        color: "#28a745"
        width: 2
      mode: lines
      visible: true
    trajectory_center:
      marker: 
        size: 4
        color: "#ffc107"
      line: 
        color: "#28a745"
        width: 2
      mode: markers
      visible: true
    limit.min:
      line: 
        color: "#dc3545"
        width: 5
        dash: dash
      mode: lines
      visible: true
    limit.max:
      line: 
        color: "#6c757d"
        width: 5
        dash: dash
      mode: lines
      visible: true
    envelope:
      marker: 
        size: 3
        color: "#28a745"
      line: 
        color: "#28a745"
        width: 2
      mode: lines
      visible: true
    end_effector:
      marker: 
        size: 5
        color: "#495057"
      line: 
        color: "#495057"
        width: 7
      visible: true
    CoG:
      marker:
        size: 4
        color: "#000000"
        symbol: circle
      mode: markers
      visible: true
    trajectory.path:
      marker: 
        size: 3
        color: "#28a745"
      line: 
        color: "#28a745"
        width: 3
      mode: lines
      visible: true
    trajectory.end_effector:
      marker: 
        size: 6
        color: "#000000"
      line: 
        color: "#000000"
        width: 3
      mode: lines
      visible: false

settings:
  debug_mode: false
  pattern_properties_enable: false
  trace_resolution_default: 400
  trace_margin: 0.15
  pattern_properties_enable: true
  pattern_properties_lookup: [yaxis, xaxis]
  pattern_properties_exclusions: [zaxis]
  symmetrical_yaxis: false
  animation_frame_rate: 20
  animation_duration: 1.0